# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Runs release job only on version tags like v1.0.0

jobs:
  security-check:
    name: Scan for Secrets
    runs-on: debian-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Scan for Secrets with TruffleHog
        uses: trufflesecurity/trufflehog@v3
        with:
          path: .
          base: origin/main

      - name: Fail if Secrets Found
        run: echo "Secrets detected! Fix before releasing." && exit 1
        if: failure()

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: security-check  # Runs only if security check passes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Tests
        run: go test ./...

      - name: Build Project
        run: go build -o bin_test/zelio_binary ./dev/src

  release:
    name: Release Build
    runs-on: ubuntu-latest
    needs: build  # Only runs if build passes
    if: startsWith(github.ref, 'refs/tags/v')  # Only run on version tags

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Remove Logs and .git Folder
        run: |
          find . -name "*.log" -type f -delete
          rm -rf .git
          echo "Logs and .git folder removed."

      - name: Upload Release Binary
        uses: softprops/action-gh-release@v2
        with:
          files: bin_test/zelio_binary
          token: ${{ secrets.GITHUB_TOKEN }}
